### ISSUE TITLE
Customized Widgets Problems

### ISSUE THREAD

**Issue by Kuriad** [abhibagul/Rina-Blogger-Template#1]
Hello. Am experiencing problems with the customized widgets, initially i they were functioning well but after 2 days they become empty. They are not showing the posts as they should. 
![zemirah Customized widgets](https://user-images.githubusercontent.com/60355041/73516665-3fdc8600-440a-11ea-9254-27e10b750af4.PNG)

**Comment by abhibagul** [comment]
Can you share the url for the blog.

**Comment by Kuriad** [comment]
hello. my blog is zemirahkenya.co.ke

**Comment by Kuriad** [comment]
I have added the customize widget called Music Tips. the view all function
is functioning well. but the widget shows a blank space on homepage

**Comment by abhibagul** [comment]
Try converting recently posted post for the respective label to draft since the error occurred. Seems like it is having a problem gathering some content from API.

**Comment by joyto39** [comment]
NOP! I have tryed with basic templet and created post with a level trevel but its not working though i have seen that Live demo is working....
![blog](https://user-images.githubusercontent.com/63514766/79051637-c73a4700-7c4e-11ea-8acc-f990fe9f40af.png)
Pls help.
url is https://theamtest123.blogspot.com/

**Comment by abhibagul** [comment]
It is happening as jquery is not loading before. Please use the updated version of the template.

**Comment by joyto39** [comment]
I have downloaded it from github.... know its free but will be breatful if you support to solve this issue

**Comment by abhibagul** [comment]
@joyto39 I check it over the url of blog. Noticed it as the older version of template. Update to the latest version.
